### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Wats0ns** [MyceliumGear/cashila-api#1]
Hi,
so I have a simple code using cashila-API, and everything I do give me this error : 

``` ruby
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/cashila-api-0.1.0/lib/cashila-api/client.rb:24: syntax error, unexpected tLABEL, expecting ')' (SyntaxError)
    def initialize(client_id:, token: nil, secret: nil, ur...
                             ^
/var/lib/gems/1.9.1/gems/cashila-api-0.1.0/lib/cashila-api/client.rb:24: Can't assign to nil
...tialize(client_id:, token: nil, secret: nil, url: CashilaAPI...
...                               ^
/var/lib/gems/1.9.1/gems/cashila-api-0.1.0/lib/cashila-api/client.rb:24: Can't assign to nil
...t_id:, token: nil, secret: nil, url: CashilaAPI::TEST_URL)
...                               ^
/var/lib/gems/1.9.1/gems/cashila-api-0.1.0/lib/cashila-api/client.rb:24: syntax error, unexpected ')', expecting keyword_end
/var/lib/gems/1.9.1/gems/cashila-api-0.1.0/lib/cashila-api/client.rb:41: syntax error, unexpected tLABEL, expecting ')'
    def sync_account(email:, details:)
                           ^
/var/lib/gems/1.9.1/gems/cashila-api-0.1.0/lib/cashila-api/client.rb:55: unknown type of %string
      %i{gov-id-front gov-id-back residence}.map do |key|
         ^
/var/lib/gems/1.9.1/gems/cashila-api-0.1.0/lib/cashila-api/client.rb:55: syntax error, unexpected $end
      %i{gov-id-front gov-id-back residence}.map do |key|
         ^
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/cashila-api-0.1.0/lib/cashila-api.rb:2:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from cash.rb:2:in `<main>'
```

Maybe I'm doing something wrong, but I run into this every time I launch a code using the API, so...

**Comment by AlexanderPavlenko** [comment]
> ruby 1.9.1

That's the problem. Current ruby version is 2.2.1.
Not sure whether we'll support 1.9.

**Comment by Wats0ns** [comment]
Oh sorry, still forgot that Ubuntu repos are rarely up to date ;-)
